import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/css/global.css";
import "@/css/embla.css";

const marvinRegular = localFont({
  src: "../fonts/Marvin.ttf",
  variable: "--font-marvin-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${marvinRegular.variable} antialiased text-shadow-contur`}>
        {children}
      </body>
    </html>
  );
}
